### ISSUE TITLE
How does this project run python cold of youtube-dl?

### ISSUE THREAD

**Issue by ZhangKuixun** [Redwid/android-youtube-dl#1]
hello, @Redwid 
How does this project run python cold of youtube-dl?
I don't found youtube-dl cold?

I need to use android call youtube-dl to download video. There have been many ways to integrate youtube-dl code on Android, but they all failed, I don't know how you integrate it. please

**Comment by ZhangKuixun** [comment]
I need to use android call python. There have been many ways to integrate youtube-dl code on Android, but they all failed, I don't know how you integrate it. please

**Comment by Redwid** [comment]
Hello,
I've done this through python-for-android project: https://github.com/kivy/python-for-android
It has python binaries that could be run on ARM architecture. Your python script will be executed by using jni integration.
It was a quite tricky to make this work (a lot of compilation parameters to be try and a lot of dependencies to be resolved).

If you like you could use android-youtube-dl/lib/ directly in your application.
Integration sample you could find in android-youtube-dl/app/ folder.

**Comment by ZhangKuixun** [comment]
Excellent, you're wonderful.
1. Will this be charged? 
2. but I didn't see youtube-dl's ".so" file and code?
3. How to update its code with youtube-dl?

**Comment by Redwid** [comment]
1. It's free to use;
2. The youtube-dl python scripts packed as zip and placed inside assets folder: 
https://github.com/Redwid/android-youtube-dl/tree/master/lib/src/main/assets
Why? That is python-for-android team solution. The ".so" libraries are only for python, crypto and ssl, could be found there: 
https://github.com/Redwid/android-youtube-dl/tree/master/lib/src/main/jniLibs 
3. You need to follow steps described here: https://github.com/Redwid/android-youtube-dl#update
And do update forked copy for youtube-dl project, instruction is here: https://help.github.com/articles/syncing-a-fork/

**Comment by ZhangKuixun** [comment]
Thanks, I try it.
Maybe, I have many questions.

**Comment by ZhangKuixun** [comment]
1.I have error:
> yihuyang:pythonforandroid zhangkuixun$ sh clean-build-copy.sh
> [INFO]     Clean
> Traceback (most recent call last):
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/toolchain.py", line 11, in <module>
>     from pythonforandroid.build import DEFAULT_NDK_API, DEFAULT_ANDROID_API
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/build.py", line 10, in <module>
>     import sh
> ImportError: No module named sh
> [INFO]     Clean done
> [INFO]     Build [armeabi-v7a]
> Traceback (most recent call last):
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/toolchain.py", line 11, in <module>
>     from pythonforandroid.build import DEFAULT_NDK_API, DEFAULT_ANDROID_API
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/build.py", line 10, in <module>
>     import sh
> ImportError: No module named sh
> Traceback (most recent call last):
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/toolchain.py", line 11, in <module>
>     from pythonforandroid.build import DEFAULT_NDK_API, DEFAULT_ANDROID_API
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/build.py", line 10, in <module>
>     import sh
> ImportError: No module named sh
> cp: directory /Users/zhangkuixun/pythonforandroid/build/libs does not exist
> cp: /Users/zhangkuixun/.python-for-android/dists/youtube_dl_wrapper/src/main/assets/: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/assets/.gitkeep: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2_image.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2_mixer.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2_ttf.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2_image.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2_mixer.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2_ttf.so: No such file or directory
> [INFO]     Build [armeabi-v7a] done
> [INFO]     Build [arm64-v8a]
> Traceback (most recent call last):
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/toolchain.py", line 11, in <module>
>     from pythonforandroid.build import DEFAULT_NDK_API, DEFAULT_ANDROID_API
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/build.py", line 10, in <module>
>     import sh
> ImportError: No module named sh
> Traceback (most recent call last):
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/toolchain.py", line 11, in <module>
>     from pythonforandroid.build import DEFAULT_NDK_API, DEFAULT_ANDROID_API
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/build.py", line 10, in <module>
>     import sh
> ImportError: No module named sh
> mkdir: /Users/zhangkuixun/pythonforandroid/build: File exists
> cp: directory /Users/zhangkuixun/pythonforandroid/build/libs does not exist
> cp: /Users/zhangkuixun/.python-for-android/dists/youtube_dl_wrapper/src/main/assets/: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/assets/.gitkeep: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2_image.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2_mixer.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/armeabi-v7a/libSDL2_ttf.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2_image.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2_mixer.so: No such file or directory
> rm: /Users/zhangkuixun/pythonforandroid/build/libs/arm64-v8a/libSDL2_ttf.so: No such file or directory
> [INFO]     Build [arm64-v8a] done
> cp: /Users/zhangkuixun/pythonforandroid/build/assets/: No such file or directory
> cp: /Users/zhangkuixun/pythonforandroid/build/libs/: No such file or directory
> [INFO]     Build done

2. I don't know `Find you new python and youtube-dl package in /libs/src/main/assets/private.mp3 and native libraries in /libs/src/main/jniLibs/`

3. My youtube-dl script is placed in which folder of python-for-android, and then compressed and compiled for youtube-dl script
@Redwid

**Comment by Redwid** [comment]
You have dependency issue.
ImportError: No module named sh
You need to resolve that before build.

**Comment by ZhangKuixun** [comment]
Hello, @Redwid I install `sh` and execute `sudo easy_install sh`
download error: 

> $ sudo easy_install sh
> Password:
> Searching for sh
> Reading https://pypi.python.org/simple/sh/
> Download error on https://pypi.python.org/simple/sh/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
> Couldn't find index page for 'sh' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
> No local packages or download links found for sh
> error: Could not find suitable distribution for Requirement.parse('sh')

Has not been solved it.
@Redwid I need your help to resolve that, we have a time lag, I'm leaving work, it hasn't been solved in a day. but, today I want to solve this problem.

**Comment by ZhangKuixun** [comment]
@Redwid Can you help me build a "private.mp3" using the new youtube-dl? I use the video information you get from your current lib and can't play it after downloading.

**Comment by Redwid** [comment]
Sorry I've used pip/pip3 to install dependencies. Have no experience with easy_install.

Are you getting video info and playing video from the same host (ip)?

**Comment by ZhangKuixun** [comment]
@Redwid 
I built [https://github.com/kivy/python-for-android](https://github.com/kivy/python-for-android)  successfully, but how to build other ABI versions of `libcrypto1.0.2h.so` and `libssl1.0.2h.so`. I want to build all the so libraries corresponding to ABI

**Comment by Redwid** [comment]
Guys at https://github.com/kivy/python-for-android could help you.
