### ISSUE TITLE
Error when use app

### ISSUE THREAD

**Issue by ChFarrelMK** [Redwid/android-youtube-dl#10]
Text representation of error dialog follows:

ERROR
Unable to finish request for the url: https://youtu.be/qvMerFd3FUE
{"result":"DownloadError"}

**Comment by Redwid** [comment]
Fixed, updated code base to the latest youtube-dl.
Please use version 1.0.1: https://github.com/Redwid/android-youtube-dl/releases/tag/20190424124801-1ab3a5e
