### ISSUE TITLE
app Crashing

### ISSUE THREAD

**Issue by xibr** [Redwid/android-youtube-dl#11]
I found this apk [https://github.com/Redwid/android-youtube-dl/releases/download/20191214160306-a901cd0/app-debug.apk](https://github.com/Redwid/android-youtube-dl/releases/download/20191214160306-a901cd0/app-debug.apk) 

![Screenshot_20191215-015614_YouTube Vanced](https://user-images.githubusercontent.com/20098154/70855117-c1ba3380-1ede-11ea-8448-4ccc91c390f4.jpg)

**Comment by Redwid** [comment]
Could you please provide cat log and link to video?
