### ISSUE TITLE
The current youtube-dl is too old

### ISSUE THREAD

**Issue by ZhangKuixun** [Redwid/android-youtube-dl#2]
The current youtube-dl is too old, Can you compile one with a new "private.mp3"?
@Redwid

**Comment by Redwid** [comment]
What commit you are looking for?
My youtube-dl has the latest commit number: [2e1280ed432257244ea52a47efe6a7f0e226b897](https://github.com/Redwid/youtube-dl/commits/master)

**Comment by ZhangKuixun** [comment]
I want to use the latest version of youtube-dl to compress and generate different versions of libraries, because youtube-dl updates the code in real time for different websites. Your YouTube-dl code is too old. I've always wanted to do your update, but I can't do your update. And you want an x86 version of so

**Comment by ZhangKuixun** [comment]
This is I changed your clean-build-copy.sh. I use python3, I want use python of host, but I can't install pip and sh.

```
clean() {
echo "[INFO]     Clean"
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 $p4a clean_builds
rm -rfv $distFolder
rm -rfv $PWD/build
echo "[INFO]     Clean done"
}

build() {
echo "[INFO]     Build [$1]"
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 $p4a clean_builds
rm -rfv $distFolder
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 $p4a apk --private $pythonApp --dist_name=$pythonAppDistName --package=$pythonAppPackageName --name=$pythonAppName --version=1 --ndk_dir $ndkDir --ndk_version r10e --requirements=android,pyopenssl,pycrypto,openssl,cloudpickle --android_api=27 --arch=$1 --java-build-tool gradle
copy_libs
copy_assets
echo "[INFO]     Build [$1] done"
}

```

**Comment by Redwid** [comment]
I'm using python 2.7.10 for build. May that will make difference for you. It's better to try.

I'm using this library constantly without any issues. So, my old youtube-dl code works perfectly fine for me (for a quite wide numbers of channels and videos). In general I'm planning update if video info extraction will not work as expected. Do you have any links that I could test?

I'm not able to build x86 arch as well. If that is a must for you, I recommend you to search for another library. Or try to get help from [python-for-android](https://github.com/kivy/python-for-android) team.

**Comment by ZhangKuixun** [comment]
eg: [https://www.youtube.com/watch?v=RHMm7-uuZZ0&app=desktop](https://www.youtube.com/watch?v=RHMm7-uuZZ0&app=desktop)
many url can't get video-url

**Comment by ZhangKuixun** [comment]
这是我的python2.7.10信息：
```
$ python -V
Python 2.7.10
$ which python
/usr/bin/python
$ python3 -V
Python 3.7.1
$ which python3
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
```
我想使用和你一样路径的python，如果使用你一样路径的python，就是mac系统下面的python，它没有pip和sh，并且我也无法安装pip和sh

**Comment by Redwid** [comment]
Your url info:
![device-2018-12-18-101037](https://user-images.githubusercontent.com/10167374/50147166-5e86c880-02ad-11e9-96d2-85eb78655b4f.png)

And all links is working for me.
For example #43 640x360 (medium) start playing in chrome:
![device-2018-12-18-101301](https://user-images.githubusercontent.com/10167374/50147278-a1e13700-02ad-11e9-9a34-18bc896241e7.png)

**Comment by ZhangKuixun** [comment]
I'm checking my code.

**Comment by Redwid** [comment]
Have you build and install my android-youtube-dl apk? Have you tested sharing from youtube app to android-youtube-dl app?

**Comment by ZhangKuixun** [comment]
error:
 
Traceback (most recent call last):
   File "/Volumes/disk/youtube-dl/youtube_dl/main.py", line 19, in <module>
   File "/Volumes/disk/youtube-dl/youtube_dl/__init__.py", line 482, in main
   File "/Volumes/disk/youtube-dl/youtube_dl/__init__.py", line 463, in _real_main
   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 1999, in download
   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 851, in process_ie_result
   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 1629, in process_video_result
   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 1700, in process_info
   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 730, in _match_entry
   File "/Volumes/disk/youtube-dl/youtube_dl/utils.py", line 1350, in __contains__
   File "/Volumes/disk/youtube-dl/youtube_dl/utils.py", line 1313, in date_from_str
 TypeError: attribute of type 'NoneType' is not callable

**Comment by ZhangKuixun** [comment]
> Have you build and install my android-youtube-dl apk? Have you tested sharing from youtube app to android-youtube-dl app?

Yes, I download your android-youtube-dl android. I don't tested sharing from youtube app to android-youtube-dl app, but I test sharing form My app to android-youtube-dl app, It's going to crash, but I didn't read the log.

**Comment by ZhangKuixun** [comment]
really many url can't get video-url. I just forgot a lot of websites.

[https://www.dailymotion.com/video/x6xwk6y?playlist=x64re9_xid](https://www.dailymotion.com/video/x6xwk6y?playlist=x64re9_xid)
this url can't get video-url

**Comment by Redwid** [comment]
Sorry, I'm not interesting in dailymotion. You could find yourself what is wrong and create pull request with a fix.

**Comment by ZhangKuixun** [comment]
do you have Email or WeChat, It's very inconvenient for call you.

**Comment by ZhangKuixun** [comment]
Do you know can't install sh.
```
$ pip install sh
Collecting sh
  Could not fetch URL https://pypi.python.org/simple/sh/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement sh (from versions: )
No matching distribution found for sh
```

**Comment by Redwid** [comment]
Hello @ZhangKuixun 
It's important to use NDK r16b.
I've added set up instruction to my build script.

**Comment by Redwid** [comment]
Updated to release 2019.01.23:  7cbfd98516c2632984c60f785d437d0f10e76841
