### ISSUE TITLE
error when attempting to use app

### ISSUE THREAD

**Issue by hyperlogos** [Redwid/android-youtube-dl#5]
Text representation of error dialog follows:

ERROR
Unable to finish request for the url: https://youtu.be/TEn7oZg-_Jc
{"result":"Error file is not exist: /data/user/11/org.redwid.android.youtube.dl.app/files/youtube_dl/youtube_dl.done"}
                     OK

Perhaps you could give me the top output of sdkmanager --list so I can match your build environment? I am on Debian 9.

**Comment by Redwid** [comment]
Most probably youtube-dl Python script failed to process your link and didn't create any output files like: youtube_dl.done and  youtube_dl.json, please see source file: https://github.com/Redwid/android-youtube-dl/blob/master/lib/src/main/java/org/redwid/android/youtube/dl/YoutubeDlWorker.java

Your link is working for me. Meta info:
![device-2019-01-07-105637](https://user-images.githubusercontent.com/10167374/50764561-fa7f7080-126a-11e9-9c92-9e1686db367f.png)

And 720p link loaded in google chrome:
![device-2019-01-07-105727](https://user-images.githubusercontent.com/10167374/50764594-17b43f00-126b-11e9-8f22-17a10c5e14a7.png)
