### ISSUE TITLE
Twitch Issue

### ISSUE THREAD

**Issue by coveroid** [Redwid/android-youtube-dl#8]
First Thanks for your work, i'm getting an error after second sharing from twitch for exemple with this url : https://www.twitch.tv/streamerhouse

**Comment by Redwid** [comment]
Logs please?

**Comment by coveroid** [comment]
This happens only after second use of youtube-dl, I tried without cache option but didnt solve issue :

> 2019-04-19 21:26:38.332 16256-17385/com.test.app I/python: run PyRun_SimpleFile begin
> 2019-04-19 21:26:40.116 16256-17385/com.test.app I/python2.7: Traceback (most recent call last):
> 2019-04-19 21:26:40.116 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/main.py", line 19, in <module>
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/__init__.py", line 482, in main
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/__init__.py", line 463, in _real_main
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 2003, in download
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/extractor/twitch.py", line 605, in _real_extract
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7:   File "/Volumes/disk/youtube-dl/youtube_dl/utils.py", line 1225, in parse_iso8601
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python2.7: TypeError: attribute of type 'NoneType' is not callable
> 2019-04-19 21:26:40.117 16256-17385/com.test.app I/python: run PyRun_SimpleFile end

**Comment by Redwid** [comment]
Is that works on your desktop?

**Comment by coveroid** [comment]
Let's say, I open the brower , i go to twitch , i choose a live and i share it to your app, your app gonna works, and now let's say i'm gonna share an other twitch live , i'm gonna get an error on your app ("error file is not exist /data/user/0/org.redwid ..../ youtube_dl.done) or on logcat the log of my previous post

**Comment by coveroid** [comment]
I tried to fix it without sucess ... i saw it could be linked to a python bug ... 
So i tried the workaround : https://bugs.python.org/issue27400
https://stackoverflow.com/questions/40392842/typeerror-in-strptime-in-python-3-4

Off course, i adapted in (utils.py) to the context but everytime after compile, i got the same error and exact same line, like if nothing on file has been changed , even if completely modify the function str_date in youtube_dl/utils.p at line 1357

Could you please give a look and try on your side, i supect some files left from compilation on my VM who let with same results ... Thanks

**Comment by coveroid** [comment]
Third message, i hope get at least an answer this time ... I still got same problem and keep trying to fixe it but i need your help, can you explain me why i still get same message when i change the function totaly and the place of it in the file, i even delete my VM and start from scratch, are the youtube-dl files dowloaded somewehere during compilation ? Please take few minutes to answer me

**Comment by Redwid** [comment]
Are you doing clean up before running build?
As python for android create a cache and then doing build from this cache.
Check utils.py inside this folder:
For mac: "$HOME/.python-for-android/dists/$pythonAppDistName"
For Liniux: "$HOME/.local/share/python-for-android/dists/$pythonAppDistName"

**Comment by coveroid** [comment]
I've done that already, he problem was coming from Android Studio and myself, each time i compile app, i tough the application was totaly uninstalled but its not the case,i"ve to uninstall it manually. i realise that after 2 days ...  i feel realluy stupid about it, but now  its works !
