### ISSUE TITLE
openssl lib is not compatible with 32 bits (armeabi-v7a)

### ISSUE THREAD

**Issue by coveroid** [Redwid/android-youtube-dl#9]
```
04-16 16:48:21.759 2468-2503/org.redwid.android.youtube.dl.app I/python2.7:   File "/Users/viacheslav.vdovenko/.python-for-android/build/other_builds/python2-openssl/arm64-v8a__ndk_target_21/python2/python-install/lib/python2.7/io.py", line 60, in <module>
04-16 16:48:21.760 2468-2503/org.redwid.android.youtube.dl.app I/python2.7: ImportError: dlopen failed: "/data/data/org.redwid.android.youtube.dl.app/files/youtube_dl/lib/python2.7/lib-dynload/_io.so" is 64-bit instead of 32-bit
```

Thanks again for your code, i hope you gonna be able to resolve these issues cause i plan to develop an app based on your code, unfortunately this is too complex to me. But Seems like openssl cause trouble with armeabi-v7a.

**Comment by Redwid** [comment]
Hello, could you please post reproducing steps?
What device or emulator are you using?

**Comment by coveroid** [comment]
Hello Redwid, Thanks for your answer, I used armeabi-v7a / api 22 Image on Nexus 6 from SDK, it's really realy slow but this its not linked from your code and to produce the error i was just sharing a link from youtube to the app

**Comment by Redwid** [comment]
Right, found the issue.
So my assumption that /android-youtube-dl/lib/src/main/assets/private.mp3 has cpu independent code was wrong.

Tree workarounds:
1. Use arm64 device for testing ;)
2. Rebuild https://github.com/Redwid/python-for-android and use private.mp3 from armeabi-v7a;
3. Rebuild python-for-android and change android-youtube-dl to use different private.mp3 per cpu architecture (feel free to create PR for that :)).

**Comment by coveroid** [comment]
Tanks for your answers, i tried hard to install sdk and compile with clean-build-copy.sh but i cant install sdk on linux, i go errors :

`Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found , i tried to fix it but didnt works
`

So could you please upload the private.mp3 coresponding to armeabi-v7a ?

**Comment by coveroid** [comment]
after spending all day on it ... I finnaly been able to compile but the assets folder  still empty, i really need your help 

> [INFO]:    target /root/.local/share/python-for-android/build/libs_collections/youtube_dl_wrapper/armeabi-v7a/libpymodules.so
[INFO]:    -> directory context /home/alex/~/Downloads/android-ndk-r16b/platforms/android-23/arch-arm/usr/lib
objs_paths are ['/root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python2/collated_objects']
[INFO]:    -> running python2.7 -shared -O3 -o /root/.local/share/python-for-android/build/libs_collections/youtube_dl_wrapper/armeabi-v7a/libpymodules.so /root/.local/share/p...(and 852 more)
[INFO]:    <- directory context /home/alex
[INFO]:    # Postbuilding recipes
[INFO]:    Postbuilding hostpython2 for armeabi-v7a
[INFO]:    Postbuilding openssl for armeabi-v7a
[INFO]:    Postbuilding sdl2_image for armeabi-v7a
[INFO]:    Postbuilding sdl2_mixer for armeabi-v7a
[INFO]:    Postbuilding sdl2_ttf for armeabi-v7a
[INFO]:    Postbuilding python2 for armeabi-v7a
[INFO]:    Postbuilding pycrypto for armeabi-v7a
[INFO]:    Postbuilding sdl2 for armeabi-v7a
[INFO]:    Postbuilding setuptools for armeabi-v7a
[INFO]:    Postbuilding android for armeabi-v7a
[INFO]:    Postbuilding pyopenssl for armeabi-v7a
[INFO]:    # Installing pure Python modules
[INFO]:    There are no Python modules to install, skipping
[INFO]:    # Creating Android project (sdl2)
[INFO]:    Copying SDL2/gradle build for armeabi-v7a
[INFO]:    -> running rm -rf /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    -> running cp -r /root/.local/share/python-for-android/build/bootstrap_builds/sdl2-python2 /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    -> directory context /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    <- directory context /home/alex
[INFO]:    -> directory context /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    Copying Python distribution
[INFO]:    -> running python.host -OO -m compileall /root/.local/share/python-for-android/build/python-installs/youtube_dl_wrapper
[INFO]:    -> running cp -a /root/.local/share/python-for-android/build/python-installs/youtube_dl_wrapper ./python-install                                                                                
[INFO]:    Copying libs
[INFO]:    -> running cp -a /root/.local/share/python-for-android/build/libs_collections/youtube_dl_wrapper/armeabi-v7a/libssl1.0.2h.so libs/armeabi-v7a
[INFO]:    -> running cp -a /root/.local/share/python-for-android/build/libs_collections/youtube_dl_wrapper/armeabi-v7a/libcrypto1.0.2h.so libs/armeabi-v7a
[INFO]:    -> running cp -a /root/.local/share/python-for-android/build/libs_collections/youtube_dl_wrapper/armeabi-v7a/libpython2.7.so libs/armeabi-v7a
[INFO]:    -> running cp -a /root/.local/share/python-for-android/build/libs_collections/youtube_dl_wrapper/armeabi-v7a/libpymodules.so libs/armeabi-v7a
[INFO]:    Copying java files
[INFO]:    -> running cp -a /root/.local/share/python-for-android/build/javaclasses/youtube_dl_wrapper src/main/java
[INFO]:    Filling private directory
[INFO]:    lib dir does not exist, making
[INFO]:    -> running cp -a python-install/lib /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private
[INFO]:    -> running mkdir -p /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private/include/python2.7
[INFO]:    -> running mv libs/armeabi-v7a/libpymodules.so /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private
[INFO]:    -> running cp python-install/include/python2.7/pyconfig.h /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private/include/python2.7/
[INFO]:    Removing some unwanted files
[INFO]:    -> running rm -f /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private/lib/libpython2.7.so
[INFO]:    -> running rm -rf /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private/lib/pkgconfig
[INFO]:    -> directory context /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private/lib/python2.7
[INFO]:    -> running rm -f mimetools.pyc code.pyc copy.pyc getopt.pyc quopri.pyc imaplib.pyc token.py codeop.py pickletools.py StringIO.pyc pyclbr.py sgmllib.pyc posixpath.p...(and 24659 more)
[INFO]:    Deleting some other stuff not used on android
[INFO]:    -> running rm -rf lib2to3
[INFO]:    -> running rm -rf idlelib
[INFO]:    -> running rm -f config/libpython2.7.a
[INFO]:    -> running rm -rf config/python.o
[INFO]:    <- directory context /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    <- directory context /home/alex
[INFO]:    Stripping libraries
[INFO]:    -> running find /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private /root/.local/share/python-for-android/dists/youtube_dl_wrapper/libs -iname *.so
[INFO]:    Stripping libraries in private dir                                                                                                                                                              
[INFO]:    Frying eggs in /root/.local/share/python-for-android/dists/youtube_dl_wrapper/private/lib/python2.7/site-packages
[INFO]:    -> directory context /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    Saving distribution info
[INFO]:    <- directory context /home/alex
[INFO]:    # Your distribution was created successfully, exiting.
[INFO]:    Dist can be found at (for now) /root/.local/share/python-for-android/dists/youtube_dl_wrapper
[INFO]:    No existing dists meet the given requirements!
[INFO]:    -> directory context /root/.local/share/python-for-android/dists/youtube_dl_wrapper
BUILD FAILURE: No main.py(o) found in your app directory. This
file must exist to act as the entry point for you app. If your app is
started by a file with a different name, rename it to main.py or add a
main.py that loads it.
[INFO]     Copy assets [armeabi-v7a]
cp: cannot stat '/root/.python-for-android/dists/youtube_dl_wrapper/libs/armeabi-v7a': No such file or directory
rm: cannot remove '/home/alex/build/armeabi-v7a/jni/armeabi-v7a/libSDL2.so': No such file or directory
rm: cannot remove '/home/alex/build/armeabi-v7a/jni/armeabi-v7a/libSDL2_image.so': No such file or directory
rm: cannot remove '/home/alex/build/armeabi-v7a/jni/armeabi-v7a/libSDL2_mixer.so': No such file or directory
rm: cannot remove '/home/alex/build/armeabi-v7a/jni/armeabi-v7a/libSDL2_ttf.so': No such file or directory
cp: cannot stat '/root/.python-for-android/dists/youtube_dl_wrapper/src/main/assets/private.mp3': No such file or directory
[INFO]     Copy assets [armeabi-v7a] done
[INFO]     Make aar [armeabi-v7a]
  adding: assets/ (stored 0%)
  adding: jni/ (stored 0%)
  adding: jni/armeabi-v7a/ (stored 0%)
[INFO]     Make aar [armeabi-v7a] done
[INFO]     Build [armeabi-v7a] done

**Comment by coveroid** [comment]
I finally was able to compile without errors: but the problem is still same even with a dedicaded private.mp3 for armeabi-v7a (i commented the line who indicate to build  for arm-64 on cleanbuild.sh) , i cant send to you the file but does this issue really interest you ?

**Comment by Redwid** [comment]
I'm about to set travis-ci for building that dependencies, then going to change apk to use two different private.mp3 per architecture.

**Comment by coveroid** [comment]
I have no idea about what travis-ci is unfortunately, but as I tried to
explain I compiled youtube dl for the dedicated architecture amreabi, thanks
to your script. I was able to generate the private.mp3 replace it in asset
project but unfortunately msg error still same (64 bits instead of 32bits)
...

**Comment by coveroid** [comment]
Last errors replacing generated .java assets and jni  with files from compilation:

> 
```
04-18 23:36:22.677 2203-2324/com.test.app W/linker: libmain.so: unused DT entry: type 0x6ffffffe arg 0x9d0
04-18 23:36:22.679 2203-2324/com.test.app W/linker: libmain.so: unused DT entry: type 0x6fffffff arg 0x1
04-18 23:36:22.838 2203-2324/com.test.app W/linker: libpython2.7.so: unused DT entry: type 0x6ffffffe arg 0x118c4
04-18 23:36:22.839 2203-2324/com.test.app W/linker: libpython2.7.so: unused DT entry: type 0x6fffffff arg 0x3
04-18 23:36:22.931 2203-2324/com.test.app W/linker: libssl1.0.2h.so: unused DT entry: type 0x6ffffffe arg 0x2e118
04-18 23:36:22.932 2203-2324/com.test.app W/linker: libssl1.0.2h.so: unused DT entry: type 0x6fffffff arg 0x1
04-18 23:36:22.936 2203-2324/com.test.app W/linker: libcrypto1.0.2h.so: unused DT entry: type 0x6ffffffe arg 0x2f4a4
04-18 23:36:22.937 2203-2324/com.test.app W/linker: libcrypto1.0.2h.so: unused DT entry: type 0x6fffffff arg 0x1
04-18 23:36:23.036 2203-2324/com.test.app E/art: dlopen("/data/app/com.test.app-1/lib/arm/libmain.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libcrypto1.0.2h.so"...
04-18 23:36:23.038 2203-2324/com.test.app E/art: No implementation found for void org.redwid.android.youtube.dl.YoutubeDlWorker.nativeStart(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (tried Java_org_redwid_android_youtube_dl_YoutubeDlWorker_nativeStart and Java_org_redwid_android_youtube_dl_YoutubeDlWorker_nativeStart__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_String_2
```

**Comment by Redwid** [comment]
I've made needed changes. Could you please pull latest changes, or use apk from release:
https://github.com/Redwid/android-youtube-dl/releases/tag/20190418203522-02916ad

**Comment by coveroid** [comment]
Thanks for triying to solve the issue, so i embeded your library and added :maven { url "https://dl.bintray.com/redwid/maven" }
to build.gradle , i got not special issues on arm64 but problem still similar with armeabi :

> live.app W/linker: libmain.so: unused DT entry: type 0x6ffffffe arg 0x1310
> 04-19 10:45:50.197 1851-1970/com.test.app W/linker: libmain.so: unused DT entry: type 0x6fffffff arg 0x1
> 04-19 10:45:50.222 1851-1970/com.test.app W/linker: libpython2.7.so: unused DT entry: type 0x6ffffffe arg 0x11854
> 04-19 10:45:50.222 1851-1970/com.test.app W/linker: libpython2.7.so: unused DT entry: type 0x6fffffff arg 0x3
> 04-19 10:45:50.251 1851-1970/com.test.app W/linker: libssl1.0.2h.so: unused DT entry: type 0x6ffffffe arg 0x2e0f0
> 04-19 10:45:50.251 1851-1970/com.test.app W/linker: libssl1.0.2h.so: unused DT entry: type 0x6fffffff arg 0x1
> 04-19 10:45:50.256 1851-1970/com.test.app W/linker: libcrypto1.0.2h.so: unused DT entry: type 0x6ffffffe arg 0x2f47c
> 04-19 10:45:50.256 1851-1970/com.test.app W/linker: libcrypto1.0.2h.so: unused DT entry: type 0x6fffffff arg 0x1
> 04-19 10:45:50.287 1851-1970/com.test.app E/art: dlopen("/data/app/com.test.app-2/lib/arm/libmain.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "forkpty" referenced by "libpython2.7.so"...
> 04-19 10:45:50.293 1851-1970/com.test.app E/art: No implementation found for void org.redwid.android.youtube.dl.YoutubeDlWorker.nativeStart(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String[]) (tried Java_org_redwid_android_youtube_dl_YoutubeDlWorker_nativeStart and Java_org_redwid_android_youtube_dl_YoutubeDlWorker_nativeStart__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_String_2)

also a small (bug sometimes the thread TaskWorkerThread staty block on sleep and never start)  who  i already correct previously  with simply adding a wait "loop" not really clean but it works on my case:

```
package org.redwid.android.youtube.dl;
import android.content.Context;
import org.redwid.android.youtube.dl.unpack.UnpackTask;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import timber.log.Timber;

public class TaskWorkerThread extends Thread {

    public interface TaskWorkerThreadListener {

        void onCompleteAllItems();
    }

    private final List<String> list = Collections.synchronizedList(new ArrayList<String>());

    private Context context;
    private UnpackTask unpackTask;

    private boolean active = true;

    TaskWorkerThread(final Context context) {
        this.context = context;
        start();
    }

    public void run() {
        while (active) {
            Timber.i("add(), list 5 %d", list.size());

            if (list.size()>0) {
                Timber.i("add(), list 6:  %d", list.size());

                try {
                    Timber.i("add(), list 7:  %d", list.size());

                    performTask();
                }
                catch (Exception e) {
                    Timber.e(e, "ERROR in run()");
                }
            }
            else {
                Timber.i("run() sleep");
                sleep();
            }
        }
    }

    void cancel() {
        active = false;
    }

    void add(final String valueUrl) {
        Timber.i("add(), list 0: "+valueUrl+" %d", list.size());

        Timber.i("add(), list 1: "+valueUrl+" %d", list.size());
        if(!list.contains(valueUrl)) {
            Timber.i("add(), list 2: "+valueUrl+" %d", list.size());
            list.add(valueUrl);
            Timber.i("add(), list 3: "+valueUrl+" %d", list.size());

        }
        wakeUp();
    }

    private synchronized void wakeUp() {
        Timber.i("wakeUp()");
        notify();
        //performTask();
    }

    private synchronized void sleep() {
        try {
            Timber.i("sleep() begin ...");
            wait(1000);
            notify();
        } catch (InterruptedException e) {
            Timber.i("sleep() end ...");
        }
    }

    private void performTask() {
        Timber.i("performTask()");

        if(unpackTask == null) {
            unpackTask = new UnpackTask();
            if(!unpackTask.unpack(context.getApplicationContext())) {
                unpackTask = null;
            }

        }

        final String stringUrl = list.get(0);
        Timber.i("performTask(), stringUrl: %s", stringUrl);

        final YoutubeDlWorker youtubeDlWorker = new YoutubeDlWorker();
        if(youtubeDlWorker.process(context.getApplicationContext(), stringUrl)) {
            Timber.i("performTask(), success");
        }
        list.remove(0);
        if(list.isEmpty()) {
            Timber.i("performTask(), list.isEmpty()");
            if(context instanceof TaskWorkerThreadListener) {
                Timber.i("performTask(), context instanceof TaskWorkerThreadListener");
                ((TaskWorkerThreadListener)context).onCompleteAllItems();
            }
        }
    }
}

```

**Comment by coveroid** [comment]
I found this link relating to the error: `https://github.com/aaaaalbert/sensibility-testbed/issues/8` so i deceide to give one more try with API 21, it seems working now but the load library is static so far on my project. Alrready a good news !

I plan to load libray like that with "Build.SUPPORTED_ABIS[0]".mp3
public class UnpackTask {

    public static final String PRIVATE =  Build.SUPPORTED_ABIS[0];

Edit : Solution works
